stages:
 build
 deploy

build:
stage: build
image: node:20.17
script:
 npm install
 npm run build

artifacts:
paths:
 dist/


deploy:
stage: deploy
image: node:20.17
script:
 apt-get update -y
 apt-get install -y lftp
 lftp -c "open -u $FTP_USER,$FTP_PASSWORD $FTP_HOST; mirror -R ./dist /public_html"
 npm install -g json-server@0.17.3
 npm run start:server

only:
 main
